name: setup 7-Zip action
description: download and unpack 7-Zip for gh actions
    
runs:
  using: composite
  steps:
    - name: download 7-Zip
      shell: cmd
      working-directory: ${{ runner.temp }}
      run: curl -L -o 7z2401-x64.msi https://www.7-zip.org/a/7z2401-x64.msi

    - name: unpack 7-Zip
      shell: cmd
      working-directory: ${{ runner.temp }}
      run: msiexec /a 7z2401-x64.msi /qb TARGETDIR=%cd%\7-Zip

    - name: rearrange files
      shell: cmd
      working-directory: ${{ runner.temp }}
      run: move 7-Zip\Files\7-Zip\* 7-Zip

    - name: add 7-zip to path
      shell: powershell
      run: echo "${{ runner.temp }}\7-Zip" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
